### ISSUE TITLE
simperAudioStreamer

### ISSUE THREAD

**Issue by sandip7032** [novoda/android-demos#21]
what is "mSrvBinding" in 
simperAudioStreamer -> AudioStreamService.java

Please Specify

**Comment by blundell** [comment]
It is the API for how you communicate to the `service`, what more do you need to know?

When you bind to the service you can get an instance of this class and therefore use it to perform actions in this service.

http://developer.android.com/guide/components/bound-services.html you cast the `IBinder` to this type

**Comment by sandip7032** [comment]
but the "Stub" is undefined in my code

On Fri, Oct 30, 2015 at 11:23 PM, Paul Blundell <notifications@github.com>
wrote:

> It is the API for how you communicate to the service, what more do you
> need to know?
>
> When you bind to the service you can get an instance of this class and
> therefore use it to perform actions in this service.
>
> http://developer.android.com/guide/components/bound-services.html you
> cast the IBinder to this type
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/novoda/android-demos/issues/21#issuecomment-152672519>
> .
>



-- 
*Sandip Dodiya*
*(+91) 9824811100*
*Support Engineer *
*Saurashtra Computech Limited*
*23/2 Galaxy Comm. Centre*
*Jawahar Road*
*Rajkot*
*sandip7032@gmail.com <sandip7032@gmail.com>*
*sandip7032@hotmail.com <sandip7032@hotmail.com>*

**Comment by blundell** [comment]
Can you explain more please? Maybe add some links to the code you're talking about

**Comment by blundell** [comment]
no reply in 6 months, closing
