### ISSUE TITLE
Reactive Architecture demo

### ISSUE THREAD

**Issue by malmstein** [novoda/android-demos#3]
It'd be great to have a demo showcasing how we deal with a reactive architecture. The example could parse a json and display some information in a fragment.

The goal is to show how to deal with networking calls and data treatment using a reactive approach.

**Comment by friedger** [comment]
A tiny rx demo is at https://github.com/novoda/rxpresso/tree/master/demo

**Comment by blundell** [comment]
this will appear in a new repo
